### ISSUE TITLE
Custom Gutenberg Block - Gallery Scrolling

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#12]
We need a custom gutenberg block that builds a gallery, but one that shows a single row of images and has scrollbars to move it.

It's important the interface for this looks like a native WordPress block.

## Inputs

1. Gallery of images (should work same as regular gallery block with ordering etc...).

## Output

1. Images: Array of MediaItems in WP-GQL-Gutenberg.

## Design:

On the frontend, we will style it to look like this (You do not have to build frontend Vue component):
<img width="1006" alt="Screen Shot 2021-05-23 at 4 05 30 PM" src="https://user-images.githubusercontent.com/475015/119263788-c0fff380-bbe0-11eb-89ea-6470368118b1.png">

So the idea is a long row of images, that are sized 70vw and height auto, and then a "overflow-x: auto"  container. Our frontend component will then have a "click and drag" style scroll in place on desktop, or swipe to scroll on mobile. We will use this: https://components.funkhaus.us/?path=/story/ui-scrollers-drag--default

## Notes:

I tried getting this working with ACF Blocks here: https://github.com/funkhaus/fuxt-backend/tree/master/blocks

But it didn't work in WP-GQL-Gutenberg and also the interface looks a little ad-hock. This native block request will replace this block.

**Comment by rsm0128** [comment]
@drewbaker 
I pushed a commit to https://github.com/funkhaus/fuxt-blocks to solve this problem.
Added `mediaItems` attribute to GraphQL query

**Comment by drewbaker** [comment]
Closed now that is in it's own repo
