### ISSUE TITLE
Custom Gutenberg Block - Cover with Logos

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#13]
We want a gutenberg block that is an 70vh background image, with SVG logos overlaid in front of it.

It's important this block feel like a native WordPress block.

## Inputs

1. Background Image (one image)
2. Logos (gallery of images)

## Outputs

1. Background Image (as a single MediaItem in WP-GQL)
2. Logos (array of MediaItems in WP-GQL)

## Design

We are going to use it like this on the frontend:
<img width="959" alt="Screen Shot 2021-05-23 at 4 12 52 PM" src="https://user-images.githubusercontent.com/475015/119264043-dfb2ba00-bbe1-11eb-8b4d-a22fbc7ae359.png">
<img width="956" alt="Screen Shot 2021-05-23 at 4 13 31 PM" src="https://user-images.githubusercontent.com/475015/119264063-eccfa900-bbe1-11eb-960d-ddb683d4965b.png">

The each logo will be displayed in a 200px tall, auto width box always. Vertically and horizontally centered, and allowed to wrap onto new lines if enough logos uploaded.

Mostly the logos will be SVGs, but could also be PNGs or JPGs.

**Comment by rsm0128** [comment]
Pushed a commit to https://github.com/funkhaus/fuxt-blocks to solve this problem.
Added `logos` and `backgroundImg` attributes to GraphQL query

**Comment by drewbaker** [comment]
Closed now that is in it's own repo
