### ISSUE TITLE
Make "Force text editor" switch work 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#16]
Now that we have Gutenberg the "Force text editor" switch doesn't work.

**Comment by rsm0128** [comment]
So the switch worked before, but stopped working with the recent update?

**Comment by drewbaker** [comment]
Well, yes but it's much more complicated now. Because with Gutenberg, there is no "classic editor" to fall back (I think?). 

Ideally it just disables the gutenberg editor, and goes to the old "text editor" but I don't want to do this if it requires installing a plugin. This isn't something we use very often.
![Screen Shot 2021-06-18 at 12 29 20 PM](https://user-images.githubusercontent.com/475015/122608295-d0802a00-d030-11eb-9776-2b5b6212ae75.png)

So I'm tempted to just remove it from the default ACF "developer settings".

ACF has an option on the filed group panel to disable the content editor, that actually doesn't work ether. 

The use case for this feature was we wanted it for pages that weren't designed to have any content shown other than the content from meta fields.

**Comment by drewbaker** [comment]
Not using this feature anymore, so closing it.
