### ISSUE TITLE
Has children ACF location rule

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#21]
Would be great if you could use " has child" as a ACF location rule. Would be useful for page structures like this:

```
- Cars
- - BMW
- - - i3 <-- This one should have the ACF field group
```

**Comment by isuke01** [comment]
You can add your own location rule easy to fit your needs, example from my gist: https://gist.github.com/isuke01/51f742fa15cb3e3da9f74e9de7fd5195
