### ISSUE TITLE
Integrate cookie plugin into theme for better GraphCDN support

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#23]
This is a plugin we currently use: https://github.com/MikhailRoot/samesite-cookie-manager/archive/refs/heads/master.zip

When using SSR sites with GraphCDN, we need to set the domain for cookies to `.example.com`, which isn't possible with Flywheel as they hard code the define() for `COOKIE_DOMAIN` to be the "WordPress Address (URL)".

So, I'd like to bring that code into the `/functions` directory, and upgrade it to use a settings field for the cookie domain. We have to be careful that we don't make it easy to allow the cookies to be set on a domain like "flywheelsites.com".

**Comment by drewbaker** [comment]
I've found a temp fix is to just find-replace `COOKIE_DOMAIN` in that plugin with the preferred domain works fine as a workaround.

**Comment by drewbaker** [comment]
@rsm0128 is working on this

**Comment by rsm0128** [comment]
@drewbaker I created PR #27 to arrange this.

**Comment by drewbaker** [comment]
Closed with https://github.com/funkhaus/fuxt-backend/commit/5bba037d1f5d3afdc702a46a2ef04983839de18c
