### ISSUE TITLE
SameSite Cookie Manager

### ISSUE THREAD

**Issue by liamb13** [funkhaus/fuxt-backend#24]
Getting an issue with SameSite Cookie Manager where it prevents me from logging into WordPress.

I believe this is likely an issue with the Plugin and not Fuxt. Although, I wanted to ask if anyone has experience anything similar?

What exactly is the plugin used for, is it a requirement?

**Comment by drewbaker** [comment]
SameSite Cookie Manager allows cookies to be shared between the frontend domain (often www.example.com) and the backend domain (often api.example.com). Wordpress by default would not allow the cookies to be used this way. That plugin allows you to set the cookies to `lax` or `none`, which would work accross the above domains (you can read more about SameSite cookie settings elsewhere).

But we use it on 50+ sites and it doesn't break logins. So I suspect you've got other problems.

Or you are running WP locally perhaps? In that case I'm not sure how cookies will respond as your domain is localhost. But I'd suspect setting "SameSite Cookie Manager" to `none` would work.
