### ISSUE TITLE
Page tree and Page parent ACF location rules, but for custom post types

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#25]
The default "page" type gets some useful ACF location rules, specially the "Page parent" and "Page belongs to tree" rules. Would be great if these worked for any Custom Post type that was hierarchical.

**Comment by rsm0128** [comment]
Created a [PR](https://github.com/funkhaus/fuxt-backend/pull/29/files) for this

**Comment by drewbaker** [comment]
Closed with https://github.com/funkhaus/fuxt-backend/commit/38d95fbee20f9f4677dddf8d85f169603c64fb44
