### ISSUE TITLE
Dashboard Search doesn't work

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#30]
If you disable the fuxt-backend theme, then Search works. Otherwise it redirects to the Dashboard landing page.
![Screen Shot 2022-04-12 at 3 52 33 PM](https://user-images.githubusercontent.com/475015/163067449-1fed637e-8284-40a8-b468-e586fe3d9bd1.png)

I think this is related to the Nested Pages plugin in some way, as if you disable that plugin the search works too.

**Comment by rsm0128** [comment]
@rsm0128 is working on this
