### ISSUE TITLE
ACF plugin critical error

### ISSUE THREAD

**Issue by narduin** [funkhaus/fuxt-backend#35]
Hello!

I'm trying to install fuxt with fuxt-backend.
I'm blocked at the plugin installation step by ACF. When using the auto-install, ACF pro can't be installed and throws this error:

`Something went wrong with the plugin API.`

I guess it's because I don't have a pro licence.

However, when I install the standard ACF plugin (non pro), either manually or through the plugin page, everything breaks instantly:

`There has been a critical error on this website. Please check your site admin email inbox for instructions.`

Is there a specific step I'm missing?
Thanks!

**Comment by drewbaker** [comment]
Ok that’s weird. You could try uncommenting the ACF include from the functions.php as a temp work around until I get a chance to look into this.

**Comment by drewbaker** [comment]
@narduin did you ever get this working? We've been using this on tens of sites... we have to manually install the ACF Pro plugin though obviously as it's behind a pay wall.

**Comment by narduin** [comment]
Hi!
I had not tried again since last time.
I just did and unfortunately I encountered the same errors as last time on a fresh wordpress install.

When you say "manually install the ACF Pro plugin", do you mean uploading manually from wordpress admin or directly through ftp?

**Comment by drewbaker** [comment]
I mean, the auto plugin install won’t work with ACF Pro as you need a license for it. So you have to install that any other way (upload or use FTP). 

I actually have never tried to use this theme without ACF pro… so I can try that out and see if I get the same error.

**Comment by rsm0128** [comment]
@drewbaker If site has ACF free version (not Pro version), it generates a fatal error because `acf_add_options_page` function isn't available in free version. I updated code in this PR to overcome the case.
https://github.com/funkhaus/fuxt-backend/pull/63/
