### ISSUE TITLE
NextPage returns random page

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/fuxt-backend#44]
NextPage gql query is consistently returning incorrect pages.
This is unrelated to the recent looping update which works well, as its happening on older sites that weren't updates (like soda).

Here's a query example:
<img width="1573" alt="pages-query" src="https://user-images.githubusercontent.com/13562688/204879986-34ac9809-52a5-469d-b03e-f6b911191e6f.png">

you can see from the page structure that's incorrect 
<img width="1587" alt="pages-next" src="https://user-images.githubusercontent.com/13562688/204880070-90dcbbbc-1bf5-4899-80da-c6064afba6f0.png">

NextPost is working as expected: 
<img width="1349" alt="posts-query" src="https://user-images.githubusercontent.com/13562688/204880180-35526ffa-6d34-4364-904c-d1afd65585f2.png">
<img width="1584" alt="posts-next" src="https://user-images.githubusercontent.com/13562688/204880189-21e36765-cfd9-4eec-bc47-4288bfdd7955.png">

**Comment by drewbaker** [comment]
If I understand the code that @rsm0128 wrote, this actually doesn't work for hierarchy posts anymore, which is wrong. For posts with hierarchy to them (like Pages) there would need to be much different logic.

**Comment by drewbaker** [comment]
See this function for how it worked for Pages: https://github.com/funkhaus/fuxt-backend/issues/39

**Comment by drewbaker** [comment]
Fixed with https://github.com/funkhaus/fuxt-backend/commit/7e6c95b061efbc894d4781793579c70c63a232be
