### ISSUE TITLE
Is this project Open Source?

### ISSUE THREAD

**Issue by ray-delossantos** [funkhaus/fuxt-backend#46]
Is this project Open Source?
If it is what kind of license covers this plugin?

**Comment by drewbaker** [comment]
Yeah it’s open source. What are you planning on using it for? I didn’t even think about the license to be honest. Any suggestions.

**Comment by ray-delossantos** [comment]
I want to use the theme as a Headless CMS for creating nextjs /remix websites for some clients. I have no idea about what type of license makes sense, I'm more a user of open-source frameworks than a contributor.

**Comment by drewbaker** [comment]
Yeah we’ll go for it, I guess if you worked for Amazon or something I’d care more LOL 

please let me know if there is anything you need in terms of features. You’re the first person I know of using it for a next site

**Comment by montchr** [comment]
@ray-delossantos See #53
