### ISSUE TITLE
Gutenberg editor: creating new lines of list blocks not working

### ISSUE THREAD

**Issue by madebyfabian** [funkhaus/fuxt-backend#47]
First of all, thank you for this theme! Exactly what I needed.
I noticed a small bug, which only appears when I have this theme installed.
In the Gutenberg editor, when adding a text-list block and trying to hit the `enter` key to add a new line, simply nothing happens. I also cannot create a new line manually with the mouse. The only way to fix this is to temporarly switch to another theme, add the lines I need in the Gutenberg editor, and then switch back to `fuxt`.

**Comment by drewbaker** [comment]
Glad you like it! Thanks for saying so. 

Do you get any errors in the console?

**Comment by madebyfabian** [comment]
@drewbaker Thanks for the quick response! Unfortunately, no errors at all.

Here is how it works with any other theme:

https://user-images.githubusercontent.com/32813692/214957835-4664516d-4b11-41ad-a889-437ca2de88f4.mov

And there is how it (not) works with fuxt:

https://user-images.githubusercontent.com/32813692/214957885-c069157b-91cd-447f-abc5-344f6a1313ef.mov

**Comment by madebyfabian** [comment]
https://user-images.githubusercontent.com/32813692/214958531-01de93f7-c65b-4ab5-a52b-9748cd674693.mov

**Comment by drewbaker** [comment]
So strange! What browser and OS are you using? If you disable all plugins does it fix anything?

**Comment by madebyfabian** [comment]
@drewbaker Yeah right 😄. 
- Disabling all plugins does not help
- I am Using `Brave 1.47.186 Chromium: 109.0.5414.119 (Offizieller Build)`. Tried it with Safari, same thing
- Tried to use a non-admin user account, still the same. 
- I commented out everything in the JS script https://github.com/funkhaus/fuxt-backend/blob/master/js/admin.js but that did also not have an effect.
- I commented out everything in the CSS files, also no effect

I'll continue to investigate. I mean it's not the end of the world, when I want to edit a list item I just quickly switch the theme. But it will be confusing for non-tech savvy editors 😄.

**Comment by drewbaker** [comment]
It’s really hard to imagine what is causing this, because there isn’t any JS that our theme has that would break that… but clearly it’s our theme because it works with others.

**Comment by madebyfabian** [comment]
@drewbaker Yeah. I suggest we leave this issue open, maybe I'll find the cause. Do you use the theme yourself? And notice the same? Or is it just me.

**Comment by rsm0128** [comment]
I found the reason for the issue. It was because `list-item` block was not in the whitelist.
Created a [PR](https://github.com/funkhaus/fuxt-backend/pull/48) to fix the issue
