### ISSUE TITLE
Feature request - Option to enable SVG uploads

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#49]
Currently we have a hard time allowing clients to upload SVGs (mostly used for logo walls of awards or their clients). There is some code that we have to uncomment in wp-functions.php to allow it. It's commented off by default because of the danger that allowing SVGs pose to CMS and for people that might not be aware that we've allowed them...

So, I think we should build a option into the theme that can be toggled on and off (off by default). It's should be on the "writing" options page I think. 

We should also test out uploading all the different SVG types and see what works and doesn't. Because I'm not even sure the code we have in the theme currently is the correct way to do it.

**Comment by rsm0128** [comment]
@drewbaker What about to use the [SVG support](https://wordpress.org/plugins/svg-support/) plugin instead of implementing the feature within the theme?

**Comment by drewbaker** [comment]
I'd like a checkbox on the Read page that says "Enable SVG uploads" and it basically just turns this part on or off:
https://plugins.trac.wordpress.org/browser/svg-support/tags/2.5.5/functions/mime-types.php

**Comment by rsm0128** [comment]
Hi @drewbaker 
I created a [PR](https://github.com/funkhaus/fuxt-backend/pull/50) for this feature.

**Comment by drewbaker** [comment]
Closed with #50
