### ISSUE TITLE
Next/Prev Post not working as expected

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/fuxt-backend#54]
## Issue
It appears that the nextPost and previousPost queries are returning null unexpectedly.
Here is the list of posts on Optic Sky:
<img width="1722" alt="Screen Shot 2023-04-25 at 4 06 56 PM" src="https://user-images.githubusercontent.com/13562688/234429575-f8cc0136-0d5c-418d-86cc-bf7fd59e5d65.png">
The next/prevPost gql query should return the adjacent posts in that list (see arrow).

On the post detail page you can see they are both returning null:
<img width="1719" alt="Screen Shot 2023-04-25 at 4 06 41 PM" src="https://user-images.githubusercontent.com/13562688/234429750-3098f644-e635-4e45-950c-b07ce0462d9b.png">

Previously we had issues where the query returned random posts for previous or next, but this is a new error where random posts return `null` for prev or next or both posts.

## Links
[repo](https://github.com/funkhaus/opticsky-frontend/)
[wordpress](https://opticsky-api.flywheelsites.com/wp-admin/)

**Comment by drewbaker** [comment]
The GQL query that produces the wrong Next post is this:

```
# #import "~/gql/fragments/GutenbergBlocks.gql"

query NewsDetail($uri: String!) {
    nodeByUri(uri: $uri) {
        id
        ... on Post {
            title
            excerpt
            date
            categories {
                edges {
                    node {
                        id
                        name
                        to: uri
                    }
                }
            }
            newsMeta {
                credit: talentName
            }
            #...GutenbergBlocks
            previousPost {
                node {
                    ... on Post {
                        id
                        title
                        uri
                    }
                }
            }
            nextPost {
                node {
                    ... on Post {
                        id
                        title
                        uri
                    }
                }
            }
        }
        ... on Page {
            title
            excerpt
            date
            newsMeta {
                credit: talentName
            }
            #...GutenbergBlocks
            nextPage {
                node {
                    id
                    title
                    uri
                    featuredImage {
                        node {
                            ...MediaImage
                        }
                    }
                }
            }
        }
    }
}

```

I suspect the issue might be `GutenbergBlocks` which you can find the fragment for that in Fuxt

**Comment by rsm0128** [comment]
@drewbaker I created a [PR](https://github.com/funkhaus/fuxt-backend/pull/55) for this issue
