### ISSUE TITLE
Custom cooke logic breaks login when site is cloned to staging

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#58]
When we clone a site to staging, the cookie logic seems to break the ability to login. I have to disable the theme via FTP, then login and re enable the theme.

**Comment by drewbaker** [comment]
For example see http://fuxt-backend.flywheelstaging.com/wp-admin

**Comment by rsm0128** [comment]
@drewbaker I think it's related cookie domain setting. When we migrate a site, the setting is migrated as well, but the value is for the previous site. I think it might be the reason for the issue

**Comment by drewbaker** [comment]
Just ran into this after changing the sites domain in flywheel... unable to login...

Is there some way to detect that the wordpress install URL has changed and we reset the cookie settings to default?
