### ISSUE TITLE
Disable "site health" widget by default upon theme activation

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#75]
Would be good to disable the "site health" widget by default, because it is always wrong in a headless environment and causes clients to stress out. 

![Screenshot 2023-12-14 at 4 05 56 PM](https://github.com/funkhaus/fuxt-backend/assets/475015/8971bd08-db03-4bb6-b676-383ae4270fed)

**Comment by rsm0128** [comment]
@drewbaker I created a PR for this issue. https://github.com/funkhaus/fuxt-backend/pull/77
