### ISSUE TITLE
ACF location rule "is tree" doesn't work when combined with other rules

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#8]
The "is tree" rule works on it's own, but when combined with "Page parent NOT equal too" it doesn't work.

This is the custom "is tree" rule.
https://github.com/funkhaus/fuxt-backend/blob/master/functions/acf-functions.php#L48-L55

A common use case for this is when we only want a field group to show up on deeper child pages, like:

- Directors
    - Commercials
    - Music Videos
    - Films
       - Person Name
       
Having a field group only show up on "Person name".

Alternatively it would also be good to have a "No children" location ACF filter.

**Comment by rsm0128** [comment]
@drewbaker
I checked "is tree" rule, but it works for me well.
Below is the case I tested.
![image](https://user-images.githubusercontent.com/45686588/116259351-b05e8800-a7b0-11eb-973b-c2d736e83243.png)
![image](https://user-images.githubusercontent.com/45686588/116259416-bf453a80-a7b0-11eb-8692-a716e8b7dfa1.png)
Here the field group is only available for the grand child pages which means it works fine.
Or did I misunderstand the problem?
Please check and let me know.
Thanks

**Comment by drewbaker** [comment]
@rsm0128 yes this is working, I think we had it setup wrong. Thanks man for checking.
